apo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('', include('front.urls')),
    url('', include('back.urls')),
    url('', include('usuario.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG == False:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/urls.py
from django.contrib import admin
from back import views
from django.urls import path, include


urlpatterns = [
    path('admin/home/', views.home, name='home'),
    path('admin/home/editar', views.home_editar, name='home_editar'),
    path('admin/estatuto', views.estatuto, name='estatuto'),
    path('admin/estatuto/editar', views.estatuto_editar, name='estatuto_editar'),
    path('admin/noticias', views.noticias, name='noticias'),
    path('admin/noticias/cadastrar', views.noticias_cadastrar, name='noticias_cadastrar'),
    path('admin/noticias/<int:noticia_id>/remover', views.noticias_remover, name='noticias_remover'),
    path('admin/noticias/<int:noticia_id>/editar', views.noticias_editar, name='noticias_editar'),
    path('admin/diretorias', views.diretorias, name='diretorias'),
    path('admin/diretorias/cadastrar', views.diretorias_cadastrar, name='diretorias_cadastrar'),
    path('admin/diretorias/<int:diretoria_id>/remover', views.diretorias_remover, name='diretorias_remover'),
    path('admin/diretorias/<int:diretoria_id>/editar', views.diretorias_editar, name='diretorias_editar'),
    path('admin/membros', views.membros, name='membros'),
    path('admin/membros/cadastrar', views.membros_cadastrar, name='membros_cadastrar'),
    path('admin/membros/<int:membro_id>/remover', views.membros_remover, name='membros_remover'),
    path('admin/membros/<int:membro_id>/editar', views.membros_editar, name='membros_editar'),
    path('admin/cursos', views.cursos, name='cursos'),
    path('admin/cursos/cadastrar', views.cursos_cadastrar, name='cursos_cadastrar'),
    path('admin/cursos/<int:curso_id>/remover', views.cursos_remover, name='cursos_remover'),
    path('admin/cursos/<int:curso_id>/editar', views.cursos_editar, name='cursos_editar'),
    path('admin/cadeiras', views.cadeiras, name='cadeiras'),
    path('admin/cadeiras/cadastrar', views.cadeiras_cadastrar, name='cadeiras_cadastrar'),
    path('admin/cadeiras/<int:cadeira_id>/remover', views.cadeiras_remover, name='cadeiras_remover'),
    path('admin/cadeiras/<int:cadeira_id>/editar', views.cadeiras_editar, name='cadeiras_editar'),
    path('admin/sobre', views.sobre, name='sobre'),
    path('admin/sobre/editar', views.sobre_editar, name='sobre_editar'),
    path('admin/email/enviar', views.email_enviar, name='email_enviar'),
    path('admin/cadeira/fundadores', views.cadeira_fundadores, name='cadeira_fundadores'),
    path('admin/cadeira/fundadores/cadastrar', views.cadeira_fundadores_cadastrar, name='cadeira_fundadores_cadastrar'),
    path('admin/cadeira/fundadores/<int:cadeira_fundadores_id>/remover', views.cadeira_fundadores_remover, name='cadeira_fundadores_remover'),
    path('admin/cadeira/fundadores/<int:cadeira_fundadores_id>/editar', views.cadeira_fundadores_editar, name='cadeira_fundadores_editar'),

   ]

back/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models


class Estatuto(models.Model):
	conteudo = models.TextField(max_length=1000)


class Noticia(models.Model):
	titulo = models.CharField(max_length=1000)
	subtitulo = models.CharField(max_length=1000)
	conteudo = models.CharField(max_length=40000)
	criado = models.DateTimeField(auto_now_add=True)
	modificado = models.DateTimeField(auto_now=True)
	imagem = models.ImageField(upload_to='imagens/', blank=True, null=True)


class Diretoria(models.Model):
	nome = models.CharField(max_length=1000)
	descricao = models.TextField()


class Membro(models.Model):
	nome = models.CharField(max_length=1000)
	descricao = models.CharField(max_length=1000)


class Curso(models.Model):
	nome = models.CharField(max_length=1000)
	descricao = models.CharField(max_length=1000)
	conteudo = models.CharField(max_length=1000)
	criado = models.DateTimeField(auto_now_add=True)
	modificado = models.DateTimeField(auto_now=True)


class Cadeira(models.Model):
	nome = models.CharField(max_length=1000)
	descricao = models.CharField(max_length=1000)


class Sobre(models.Model):
	titulo = models.CharField(max_length=1000)
	conteudo = models.CharField(max_length=1000)
	imagem = models.ImageField(upload_to='imagens/', blank=True, null=True)


class Home(models.Model):
	telefone = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	localizadao = models.CharField(max_length=100)
	imagem = models.ImageField(upload_to='imagens/', blank=True, null=True)


class CadeiraFundadoresTitulares(models.Model):
	nome_fundador_titular = models.CharField(max_length=150)
	nome_membro_atual = models.CharField(max_length=150)
	descricao_fundador_titular = models.CharField(max_length=250)
	descricao_membro_atual = models.CharField(max_length=250)
	imagem_membro_atual = models.ImageField(upload_to='imagens/', blank=True, null=True)
	imagem_membro_fundador = models.ImageField(upload_to='imagens/', blank=True, null=True)
	in_memorian = models.BooleanField(default=False)
	numero_da_cadeira = models.IntegerField(null=True)

back/forms.py
from django import forms

back/views.py
from django.shortcuts import render, redirect
from core.models import Estatuto, Noticia, Diretoria, Membro, Curso, Cadeira, Sobre, Home, CadeiraFundadoresTitulares
from django.core.files.storage import FileSystemStorage
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
	try:
		home = Home.objects.get(id=1)
	except:
		home = Home()
		home.save()
	return render(request, 'home.html', {'home': home})


@login_required
def home_editar(request):
	home = Home.objects.get(id=1)
	if request.method == 'POST':
		home.telefone = request.POST['telefone']
		home.email = request.POST['email']
		home.localizadao = request.POST['localizadao']
		home.save()
		return redirect('home')
	else:
		return render(request, 'home_editar.html', {'home': home})


@login_required
def estatuto(request):
	try:
		estatuto = Estatuto.objects.get(id=1)
	except:
		estatuto = Estatuto(conteudo='Digite o conteudo do estatuto')	
		estatuto.save()
	return render(request, 'estatuto.html', {'estatuto': estatuto})


@login_required
def estatuto_editar(request):
	estatuto = Estatuto.objects.get(id=1)
	if request.method == 'POST':
		estatuto.conteudo = request.POST['estatuto_conteudo']
		estatuto.save()
		return redirect('estatuto')
	else:
		return render(request, 'estatuto_editar.html', {'estatuto': estatuto })


@login_required
def noticias(request):
	noticias = Noticia.objects.all()
	lista_noticias = noticias
	lista_noticias.reverse()
	return render(request, 'noticias.html', {'noticias': lista_noticias})


@login_required
def noticias_cadastrar(request):
	if request.method == 'POST':
		imagem = request.FILES.get('imagem', False)
		if imagem:
			fs = FileSystemStorage()
			filename = fs.save(imagem.name, imagem)
			uploaded_file_url = fs.url(filename)
			noticia = Noticia(titulo=request.POST['titulo'], subtitulo=request.POST['subtitulo'], conteudo=request.POST['conteudo'], imagem=uploaded_file_url)
		else:
			noticia = Noticia(titulo=request.POST['titulo'], subtitulo=request.POST['subtitulo'], conteudo=request.POST['conteudo'], imagem=None)
		noticia.save()
		return redirect('noticias')
	else:
		return render(request, 'noticias_cadastrar.html')


@login_required
def noticias_editar(request, noticia_id):
	noticia = Noticia.objects.get(id=noticia_id)
	if request.method == 'POST':
		noticia.titulo = request.POST['titulo']
		noticia.subtitulo = request.POST['subtitulo']
		noticia.conteudo = request.POST['conteudo']
		imagem = request.FILES.get('imagem', False)
		if imagem:
			fs = FileSystemStorage()
			filename = fs.save(imagem.name, imagem)
			uploaded_file_url = fs.url(filename)
			noticia.imagem=uploaded_file_url
		noticia.save()
		return redirect('noticias')
	else:
		return render(request, 'noticias_editar.html', {'noticia': noticia})


@login_required
def noticias_remover(request, noticia_id):
	noticia = Noticia.objects.get(id=noticia_id)
	noticia.delete()
	return redirect('noticias')


@login_required
def diretorias(request):
	try:
		diretorias = Diretoria.objects.all()
	except:
		diretorias = []
	return render(request, 'diretorias.html', {'diretorias': diretorias})


@login_required
def diretorias_cadastrar(request):
	if request.method == 'POST':
		diretoria = Diretoria(nome=request.POST['nome'], descricao=request.POST['descricao'])
		diretoria.save()
		return redirect('diretorias')
	else:
		return render(request, 'diretorias_cadastrar.html')


@login_required
def diretorias_editar(request, diretoria_id):
	diretoria = Diretoria.objects.get(id=diretoria_id)
	if request.method == 'POST':
		diretoria.nome = request.POST['nome']
		diretoria.descricao = request.POST['descricao']
		diretoria.save()
		return redirect('diretorias')
	else:
		return render(request, 'diretorias_editar.html', {'diretoria':diretoria})


@login_required
def diretorias_remover(request, diretoria_id):
	diretoria = Diretoria.objects.get(id=diretoria_id)
	diretoria.delete()
	return redirect('diretorias')


@login_required
def membros(request):
	try:
		membros = Membro.objects.all()
	except:
		membros = []
	return render(request, 'membros.html', {'membros': membros})


@login_required
def membros_cadastrar(request):
	if request.method == 'POST':
		membro = Membro(nome=request.POST['nome'], descricao=request.POST['descricao'])
		membro.save()
		return redirect('membros')
	else:
		return render(request, 'membros_cadastrar.html')


@login_required
def membros_editar(request, membro_id):
	membro = Membro.objects.get(id=membro_id)
	if request.method == 'POST':
		membro.nome = request.POST['nome']
		membro.descricao = request.POST['descricao']
		membro.save()
		return redirect('membros')
	else:
		return render(request, 'membros_editar.html', {'membro': membro})


@login_required
def membros_remover(request, membro_id):
	membro = Membro.objects.get(id=membro_id)
	membro.delete()
	return redirect('membros')


@login_required
def cursos(request):
	try:
		cursos = Curso.objects.all()
	except:
		cursos = []
	return render(request, 'cursos.html', {'cursos': cursos})


@login_required
def cursos_cadastrar(request):
	if request.method == 'POST':
		curso = Curso(nome=request.POST['nome'], descricao=request.POST['descricao'], conteudo=request.POST['conteudo'])
		curso.save()
		return redirect('cursos')
	else:
		return render(request, 'cursos_cadastrar.html')


@login_required
def cursos_editar(request, curso_id):
	curso = Curso.objects.get(id=curso_id)
	if request.method == 'POST':
		curso.nome = request.POST['nome']
		curso.descricao = request.POST['descricao']
		curso.conteudo = request.POST['conteudo']
		curso.save()
		return redirect('cursos')
	else:
		return render(request, 'cursos_editar.html', {'curso': curso})


@login_required
def cursos_remover(request, curso_id):
	curso = Curso.objects.get(id=curso_id)
	curso.delete()
	return redirect('cursos')


@login_required
def cadeiras(request):
	try:
		cadeiras = Cadeira.objects.all()
	except:
		cadeiras = []
	return render(request, 'cadeiras.html', {'cadeiras': cadeiras})


@login_required
def cadeiras_cadastrar(request):
	if request.method == 'POST':
		cadeira = Cadeira(nome=request.POST['nome'], descricao=request.POST['descricao'])
		cadeira.save()
		return redirect('cadeiras')
	else:
		return render(request, 'cadeiras_cadastrar.html')


@login_required
def cadeiras_editar(request, cadeira_id):
	cadeira = Cadeira.objects.get(id=cadeira_id)
	if request.method == 'POST':
		cadeira.nome = request.POST['nome']
		cadeira.descricao = request.POST['descricao']
		cadeira.save()
		return redirect('cadeiras')
	else:
		return render(request, 'cadeiras_editar.html', {'cadeira': cadeira})


@login_required
def cadeiras_remover(request, cadeira_id):
	cadeira = Cadeira.objects.get(id=cadeira_id)
	cadeira.delete()
	return redirect('cadeiras')


@login_required
def sobre(request):
	try:
		sobre = Sobre.objects.get(id=1)
	except:
		sobre = Sobre(conteudo="")
		sobre.save()
	return render(request, 'sobre.html', {'sobre': sobre })


@login_required
def sobre_editar(request):
	sobre = Sobre.objects.get(id=1)
	imagem = request.FILES.get('imagem', False)
	if request.method == 'POST' and imagem:
		fs = FileSystemStorage()
		filename = fs.save(imagem.name, imagem)
		uploaded_file_url = fs.url(filename)
		sobre.titulo = request.POST['titulo']
		sobre.conteudo = request.POST['conteudo']
		sobre.imagem = uploaded_file_url
		sobre.save()
		return redirect('sobre')
	elif request.method == 'POST' and sobre.imagem:
		sobre.titulo = request.POST['titulo']
		sobre.conteudo = request.POST['conteudo']
		sobre.save()
		return redirect('sobre')
	else: 	
		return render(request, 'sobre_editar.html', {'sobre': sobre })


@login_required
def email_enviar(request):
	request.POST['nome']
	request.POST['email']
	email = EmailMessage(request.POST['assunto'], request.POST['mensagem'], to=['irvaynematheus@hotmail.com'])
	email.send()
	return redirect('index')


@login_required
def cadeira_fundadores(request):
	try:
		cadeira_fundadores = CadeiraFundadoresTitulares.objects.all()
	except:
		cadeiras_fundadores = []
	return render(request, 'cadeira_fundadores.html', {'cadeira_fundadores': cadeira_fundadores})


@login_required
def cadeira_fundadores_cadastrar(request):
	if request.method == 'POST':
		imagem = request.FILES.get('imagem', False)
		imagem_fundador = request.FILES.get('imagem_fundador', False)
		in_memorian = request.POST.get('in_memorian', '') == 'on'
		uploaded_file_membro_url = None
		uploaded_file_fundador_url = None

		if imagem:
			fs = FileSystemStorage()
			filename = fs.save(imagem.name, imagem)
			uploaded_file_membro_url = fs.url(filename)
		if imagem_fundador:
			fs = FileSystemStorage()
			filename = fs.save(imagem_fundador.name, imagem_fundador)
			uploaded_file_fundador_url = fs.url(filename)

		cadeira_fundadores = CadeiraFundadoresTitulares(
				nome_fundador_titular=request.POST['nome_fundador_titular'],
				nome_membro_atual=request.POST['nome_membro_atual'],
				descricao_fundador_titular=request.POST['descricao_fundador_titular'],
				descricao_membro_atual=request.POST['descricao_membro_atual'],
				imagem_membro_atual=uploaded_file_membro_url,
				imagem_membro_fundador=uploaded_file_fundador_url,
				in_memorian=in_memorian,
				numero_da_cadeira=request.POST['numero_da_cadeira'])
		
		cadeira_fundadores.save()
		return redirect('cadeira_fundadores')
	else:
		return render(request, 'cadeira_fundadores_cadastrar.html')


@login_required
def cadeira_fundadores_editar(request, cadeira_fundadores_id):
	cadeira_fundadores = CadeiraFundadoresTitulares.objects.get(id=cadeira_fundadores_id)
	if request.method == 'POST':
		cadeira_fundadores.nome_fundador_titular = request.POST['nome_fundador_titular']
		cadeira_fundadores.nome_membro_atual = request.POST['nome_membro_atual']
		cadeira_fundadores.descricao_fundador_titular = request.POST['descricao_fundador_titular']
		cadeira_fundadores.descricao_membro_atual = request.POST['descricao_membro_atual']

back/templates/cadeira_fundadores.html
{% extends "decorator.html" %}
{% block body %}

<div class="panel-body">
	<a type="button" href="{% url 'cadeira_fundadores_cadastrar' %}" class="btn btn-primary pull-right">Cadastrar</a>

</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Cadeira Fundadores Cadastradas</h3>
	</div>
	<div class="panel-body">
		<table class="table"> <thead>
			<tr>
				<th scope="col">Nome do Fundador Titular</th>
				<th scope="col">Nome do Membro Atual</th>
				<th scope="col">Descrição do Fundador Titular</th>
				<th scope="col">Descrição do Membro Atual</th>
				<th scope="col">Imagem</th>
				<th scope="col">In Memorian</th>
				<th scope="col">Opcoes</th>
			</tr>
		</thead>
		<tbody>
			{% for cadeira_fundador in cadeira_fundadores %}
			<tr>
				<td>{{ cadeira_fundador.nome_fundador_titular }}</td>
				<td>{{ cadeira_fundador.nome_membro_atual }}</td>
				<td>{{ cadeira_fundador.descricao_fundador_titular }}</td>
				<td>{{ cadeira_fundador.descricao_membro_atual }}</td>
				<td>{{ cadeira_fundador.imagem_membro_atual }}</td>
				<td>{{ cadeira_fundador.in_memorian }}</td>
				<td>
					<a class="btn btn-warning" href="{% url 'cadeira_fundadores_editar' cadeira_fundador.id %}">
						<span class="glyphicon glyphicon-pencil"></span> Editar
					</a>
					<a class="btn btn-danger" data-toggle="modal" data-target="#{{cadeira_fundador.id}}">
						<span class="glyphicon glyphicon-remove"></span> Excluir
					</a>

					<div class="modal fade" id="{{cadeira_fundador.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title" >Alerta de Confirmação</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        Tem certeza que deseja excluir?
					      </div>
					      <div class="modal-footer">
					      	<a type="button" href="{% url 'cadeira_fundadores_remover' cadeira_fundador.id %}" class="btn btn-success">Sim</a>
					        <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
					      </div>
					    </div>
					  </div>
					</div>
				</td>

			</tr>

			{% endfor %}

		</tbody></table>
	</div>
</div>

{% endblock %}

back/templates/cadeira_fundadores_editar.html
{% extends 'decorator.html' %}
{% block body %}


<form accept="{% url 'cadeira_fundadores_editar' cadeira_fundadores.id %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome_fundador_titular">Nome do Fundador Titular</label>
		<input type="text" name="nome_fundador_titular" value="{{ cadeira_fundadores.nome_fundador_titular}}" class="form-control" id="id_nome_fundador_titular" placeholder="Nome do Fundador Titular">
	</div>
	<div class="form-group">
		<label for="id_descricao_fundador_titular">Descrição do Fundador Titular</label>
		<input type="text" name="descricao_fundador_titular" value="{{ cadeira_fundadores.descricao_fundador_titular}}" class="form-control" id="id_descricao_fundador_titular" placeholder="Descrição do Fundador Titular">
	</div>
	<div class="form-group">
		<label for="id_nome_membro_atual">Nome do Membro Atual</label>
		<input type="text" name="nome_membro_atual" class="form-control" value="{{ cadeira_fundadores.nome_membro_atual}}" id="id_nome_membro_atual" placeholder="Nome do Membro Atual">
	</div>
	<div class="form-group">
		<label for="id_descricao_membro_atual">Descrição do Membro Atual</label>
		<input type="text" name="descricao_membro_atual" class="form-control" value="{{ cadeira_fundadores.descricao_membro_atual}}" id="id_descricao_membro_atual" placeholder="Descrição do Membro Atual">
	</div>
	<div class="form-group">
		<label for="id_imagem">Imagem do Membro Atual</label>
		<input type="file" name="imagem" class="form-control" id="id_imagem" value="{{ cadeira_fundadores.imagem_membro_atual}}" placeholder="Imagem">
	</div>
	<div class="form-check">
		{% if cadeira_fundadores.in_memorian %}
    		<input type="checkbox" class="form-check-input" id="id_in_memorian" checked name="in_memorian">
    	{% else %}
    		<input type="checkbox" class="form-check-input" id="id_in_memorian" name="in_memorian">
    	{% endif %}
    <label class="form-check-label" for="id_in_memorian">In Memorian</label>
  </div>
	<button class="btn btn-primary">Salvar</button>
</form>

{% endblock %}

back/templates/cadeiras_cadastrar.html
{% extends 'decorator.html' %}
{% block body %}

<form accept="{% url 'cadeiras_cadastrar' %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome">Nome</label>
		<input type="text" name="nome" class="form-control" id="id_nome" placeholder="Nome da cadeira">
	</div>
	<div class="form-group">
		<label for="id_descricao">Descrição</label>
		<input type="text" name="descricao" class="form-control" id="id_descricao" placeholder="Descrição da cadeira">
	</div>
	<button class="btn btn-primary">Salvar</button>
</form>

{% endblock %}

back/templates/cursos_cadastrar.html
{% extends 'decorator.html' %}
{% block body %}

<form accept="{% url 'cursos_cadastrar' %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome">Nome</label>
		<input type="text" name="nome" class="form-control" id="id_nome" placeholder="Nome do curso">
	</div>
	<div class="form-group">
		<label for="id_descricao">Descrição</label>
		<input type="text" name="descricao" class="form-control" id="id_descricao" placeholder="Descrição da curso">
	</div>
	<div class="form-group">
		<label for="id_conteudo">Conteúdo</label>
		<input type="text" name="conteudo" class="form-control" id="id_conteudo" placeholder="Conteúdo do curso">
	</div>
	<button class="btn btn-primary">Salvar</button>
</form>

{% endblock %}

back/templates/cursos_editar.html
{% extends 'decorator.html' %}
{% block body %}

<form accept="{% url 'cursos_editar' curso.id %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome">Nome</label>
		<input type="text" name="nome" class="form-control" id="id_nome" value="{{curso.nome}}" placeholder="Nome do curso">
	</div>
	<div class="form-group">
		<label for="id_descricao">Descrição</label>
		<input type="text" name="descricao" class="form-control" id="id_descricao" value="{{curso.descricao}}" placeholder="Descrição da curso">
	</div>
	<div class="form-group">
		<label for="id_conteudo">Conteúdo</label>
		<input type="text" name="conteudo" class="form-control" id="id_conteudo" value="{{curso.conteudo}}" placeholder="Conteúdo do curso">
	</div>
	<button class="btn btn-primary">Salvar</button>
</form>

{% endblock %}

back/templates/diretorias_cadastrar.html
{% extends 'decorator.html' %}
{% load staticfiles %}
{% block body %}

<form accept="{% url 'diretorias_cadastrar' %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome">Nome</label>
		<input type="text" name="nome" class="form-control" id="id_nome" placeholder="Nome da diretoria">
	</div>
	<div class="form-group">
		<label for="id_descricao">Descrição</label>
		<textarea id="id_descricao" name="descricao" ></textarea>
	</div>
	
	<button class="btn btn-primary">Salvar</button>

</form>

<script src="{% static "ckeditor/ckeditor.js" %}"></script>
<script>
    CKEDITOR.replace( 'id_descricao' );
</script>

{% endblock %}

back/templates/diretorias_editar.html
{% extends 'decorator.html' %}
{% load staticfiles %}
{% block body %}

<form accept="{% url 'diretorias_editar' diretoria.id %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_nome">Nome</label>
		<input type="text" name="nome" class="form-control" id="id_nome" value="{{diretoria.nome}}" placeholder="Nome da diretoria">
	</div>
	<div class="form-group">
		<label for="id_descricao">Descrição</label>
		<textarea id="id_descricao" name="descricao" >{{diretoria.descricao}}</textarea>
	</div>
	
	<button class="btn btn-primary">Salvar</button>

</form>

<script src="{% static "ckeditor/ckeditor.js" %}"></script>
<script>
    CKEDITOR.replace( 'id_descricao' );
</script>

{% endblock %}

back/templates/home_editar.html
{% extends 'decorator.html' %}
{% load staticfiles %}

{% block body %}
<div id="dvCentro">
    <form accept="{% url 'home_editar' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
			<label for="id_telefone">Telefone</label>
			<input type="text" name="telefone" class="form-control" id="id_telefone" placeholder="Telefone" value="{{home.telefone}}">
		</div>
		<div class="form-group">
			<label for="id_email">E-mail</label>
			<input type="email" name="email" class="form-control" id="id_email" placeholder="E-mail" value="{{home.email}}">
		</div>
		<div class="form-group">
			<label for="id_localizacao">Localização</label>
			<input type="text" name="localizadao" class="form-control" id="id_localizacao" placeholder="Localização" value="{{home.localizadao}}">
		</div>
		<div class="form-group">
			<label for="id_imagem">Imagem</label>
			<input type="file" name="imagem" class="form-control" id="id_imagem" placeholder="Imagem">
		</div>
		<button class="btn btn-primary">Salvar</button>
    </form>
</div>

<a href="{% url 'home'  %}" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> Cancelar</a>

{% endblock %}

back/templates/noticias_cadastrar.html
{% extends 'decorator.html' %}
{% load staticfiles %}
{% block body %}

<form accept="{% url 'noticias_cadastrar' %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="form-group">
		<label for="id_titulo">Título</label>
		<input type="text" name="titulo" class="form-control" id="id_titulo" placeholder="Título da notícia">
	</div>
	<div class="form-group">
		<label for="id_subtitulo">Subtítulo</label>
		<input type="text" name="subtitulo" class="form-control" id="id_subtitulo" placeholder="Subtítulo da notícia">
	</div>
	<div class="form-group">
		<label for="id_imagem">Imagem</label>
		<input type="file" name="imagem" class="form-control" id="id_imagem" placeholder="Imagem">
	</div>
	<div class="form-group">
		<label for="id_conteudo">Conteúdo</label>
		<textarea id="id_conteudo" name="conteudo" ></textarea>
	</div>
	<button class="btn btn-primary">Salvar</button>
</form>

<script src="{% static "ckeditor/ckeditor.js" %}"></script>
<script>
	CKEDITOR.replace( 'id_conteudo' );
</script>


{% endblock %}